; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "VWheel"
#define MyAppVersion "1.0"
#define MyAppPublisher "Adi Co."
#define MyAppExeName "VWheel.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5A3C43F8-B4E3-4A17-998B-CA799017F16E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=admin
OutputDir=S:\Otros\PROYECTO VOLANTE VIRTUAL\VWheel
OutputBaseFilename=VWheel_Server_v1.0_Installer
SetupIconFile=S:\Otros\PROYECTO VOLANTE VIRTUAL\VWheel\logo.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "S:\Otros\PROYECTO VOLANTE VIRTUAL\VWheel\VWheel\bin\x64\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "S:\Otros\PROYECTO VOLANTE VIRTUAL\VWheel\VWheel\bin\x64\Release\vJoyInterface.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "S:\Otros\PROYECTO VOLANTE VIRTUAL\VWheel\VWheel\bin\x64\Release\vJoyInterfaceWrap.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "S:\Otros\PROYECTO VOLANTE VIRTUAL\VWheel\VWheel\bin\x64\Release\VWheel.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\ASUS\Downloads\vJoy-2.2.1.1\vJoySetup.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\vJoySetup.exe"; Description: "Instalar el driver vJoy (Requerido para el Force Feedback)"; Flags: postinstall shellexec waituntilterminated
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

