; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "VWheel"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Adi Co."
#define MyAppExeName "VWheel.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5A3C43F8-B4E3-4A17-998B-CA799017F16E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequired=admin

; El instalador final ahora se guardará directo en tu carpeta "Instaladores"
OutputDir=S:\Otros\PROYECTO-VOLANTE-VIRTUAL\Instaladores
OutputBaseFilename=VWheel_Server_v1.0.1_Installer
SetupIconFile=S:\Otros\PROYECTO-VOLANTE-VIRTUAL\VWheel\logo.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "S:\Otros\PROYECTO-VOLANTE-VIRTUAL\VWheel\VWheel\bin\x64\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "S:\Otros\PROYECTO-VOLANTE-VIRTUAL\VWheel\VWheel\bin\x64\Release\vJoyInterface.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "S:\Otros\PROYECTO-VOLANTE-VIRTUAL\VWheel\VWheel\bin\x64\Release\vJoyInterfaceWrap.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "S:\Otros\PROYECTO-VOLANTE-VIRTUAL\VWheel\VWheel\bin\x64\Release\VWheel.exe.config"; DestDir: "{app}"; Flags: ignoreversion

; NUEVA RUTA DEL VJOY (Versión Brunner)
Source: "S:\Otros\PROYECTO-VOLANTE-VIRTUAL\Instaladores\vJoySetup_v2.2.2.0_Win10_Win11.exe"; DestDir: "{app}"; Flags: ignoreversion deleteafterinstall

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; SE EJECUTA EL NUEVO NOMBRE DEL INSTALADOR DE VJOY
Filename: "{app}\vJoySetup_v2.2.2.0_Win10_Win11.exe"; Description: "Install vJoy Driver (Required for Force Feedback)"; Flags: postinstall shellexec waituntilterminated
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent